// apps/react-client/src/features/employees/EmployeeDetails.tsx
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { useParams } from 'react-router-dom';
import { getEmployee } from 'crud-utils';
import { Card } from 'primereact/card';

export const EmployeeDetails = () => {
  const { employeeId } = useParams() as { employeeId: string };

  const { data: employee } = useQuery({
    queryKey: ['employee', employeeId],
    queryFn() {
      return getEmployee(employeeId);
    },
  });

  return (
    <>
      {employee && (
        <div className="h-[100vh] flex items-center justify-center">
          <div className="w-[40vw]">
            <Card
              title={employee.name}
              footer={
                <Link
                  to="/"
                  className="p-ripple p-element p-button p-component p-button-sm no-underline"
                >
                  Back
                </Link>
              }
            >
              <dl className="grid grid-cols-4 m-0">
                <dt className="col-span-4 sm:col-span-1 font-extrabold">
                  Email:
                </dt>
                <dd className="col-span-4 sm:col-span-3 ml-0 mb-2">
                  {employee.email}
                </dd>
                <dt className="col-span-4 sm:col-span-1 font-extrabold">
                  Mobile:
                </dt>
                <dd className="col-span-4 sm:col-span-3 ml-0 mb-2">
                  {employee.mobile}
                </dd>
                <dt className="col-span-4 sm:col-span-1 font-extrabold">
                  Date of Birth:
                </dt>
                <dd className="col-span-4 sm:col-span-3 ml-0 mb-2">
                  {employee.dob}
                </dd>
                <dt className="col-span-4 sm:col-span-1 font-extrabold">
                  Date Joined:
                </dt>
                <dd className="col-span-4 sm:col-span-3 ml-0 mb-2">
                  {employee.doj}
                </dd>
              </dl>
            </Card>
          </div>
        </div>
      )}
    </>
  );
};

// apps/vue-client/src/features/employees/EmployeeDetails.vue
<template>
  <div v-if="employee" class="h-[100vh] flex items-center justify-center">
    <div class="w-[40vw]">
      <Card>
        <template #title>{{ employee.name }}</template>
        <template #content>
          <dl class="grid grid-cols-4 m-0">
            <dt class="col-span-4 sm:col-span-1 font-extrabold">Email:</dt>
            <dd class="col-span-4 sm:col-span-3 ml-0 mb-2">
              {{ employee.email }}
            </dd>
            <dt class="col-span-4 sm:col-span-1 font-extrabold">Mobile:</dt>
            <dd class="col-span-4 sm:col-span-3 ml-0 mb-2">
              {{ employee.mobile }}
            </dd>
            <dt class="col-span-4 sm:col-span-1 font-extrabold">Date of Birth:</dt>
            <dd class="col-span-4 sm:col-span-3 ml-0 mb-2">
              {{ employee.dob }}
            </dd>
            <dt class="col-span-4 sm:col-span-1 font-extrabold">Date Joined:</dt>
            <dd class="col-span-4 sm:col-span-3 ml-0 mb-2">
              {{ employee.doj }}
            </dd>
          </dl>
        </template>
        <template #footer>
          <RouterLink
            to="/"
            class="p-ripple p-element p-button p-component p-button-sm no-underline"
            >Back</RouterLink
          >
        </template>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { useRoute, RouterLink } from 'vue-router';
import { getEmployee } from 'crud-utils';

import Card from 'primevue/card';

const route = useRoute();
const employeeId = route.params['employeeId'];
const { data: employee } = useQuery({
  get queryKey() {
    return ['employee', employeeId];
  },
  queryFn() {
    return getEmployee(employeeId as string);
  },
});
</script>
