// apps/react-client/src/features/employees/EmployeeForm.tsx
import { InputText } from 'primereact/inputtext';
import { Button } from 'primereact/button';
import { useForm, Controller } from 'react-hook-form';
import { object, string, InferType } from 'yup';
import { yupResolver } from '@hookform/resolvers/yup';
import { type Employee } from 'crud-utils';
import { format } from 'date-fns';

import { Calendar } from 'primereact/calendar';
import { Nullable } from 'primereact/ts-helpers';
import { MutableRefObject } from 'react';
import { Toast } from 'primereact/toast';
import { useMutation } from '@tanstack/react-query';
import { createEmployee, updateEmployee } from 'crud-utils';

const dateRegex = /^\d{2}-\d{2}-\d{4}$/;

const dateSchema = string().required().matches(dateRegex);

const schema = object({
  name: string().required(),
  email: string().required().email(),
  mobile: string().required(),
  dob: dateSchema,
  doj: dateSchema,
});

type FieldValues = InferType<typeof schema>;

type EmployeeFormProps = {
  employee?: Employee;
  onCloseModal: () => void;
  toast: MutableRefObject<Toast>;
};

export const EmployeeForm = ({
  employee,
  onCloseModal,
  toast,
}: EmployeeFormProps) => {
  const {
    register,
    control,
    formState: { errors, isValid },
    handleSubmit,
  } = useForm<FieldValues>({
    defaultValues: employee,
    resolver: yupResolver(schema),
    shouldUnregister: true,
  });

  const { mutate: createMutate } = useMutation<Employee, Error, FieldValues>({
    mutationKey: ['createEmployee'],
    mutationFn(employee) {
      return createEmployee(employee);
    },
    onSuccess() {
      showSuccessfulToast('Employee Successfully Created');
      onCloseModal();
    },
  });

  const { mutate: updateMutate } = useMutation<Employee, Error, FieldValues>({
    mutationKey: ['updateEmployee', employee?.employeeId],
    mutationFn(_employee) {
      return updateEmployee(employee!.employeeId, _employee);
    },
    onSuccess() {
      showSuccessfulToast('Employee Successfully Updated');
      onCloseModal();
    },
  });

  const submitHandler = handleSubmit((values) => {
    if (employee) {
      updateMutate(values);
      return;
    }
    createMutate(values);
  });
  const formatOutBoundDate = (outboundDate: Nullable<Date>) => {
    if (outboundDate) {
      return format(new Date(outboundDate), 'LL-dd-yyyy');
    }
    return '';
  };
  const formatInboundDate = (inboundDate?: string) => {
    if (inboundDate) {
      return new Date(inboundDate);
    }
    return null;
  };
  function showSuccessfulToast(detail: string) {
    toast.current.show({
      severity: 'success',
      summary: 'Success',
      detail: detail,
      life: 3000,
    });
  }

  return (
    <>
      <form onSubmit={submitHandler}>
        <div className="mb-5">
          <label
            htmlFor="name"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            Name
          </label>
          <InputText
            {...register('name')}
            type="text"
            id="name"
            className={`w-full ${errors.name ? 'p-invalid' : ''}`}
          />
          {errors.name && (
            <p className="text-red-600 mt-1">{errors.name?.message}</p>
          )}
        </div>
        <div className="mb-5">
          <label
            htmlFor="email"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            Email
          </label>
          <InputText
            {...register('email')}
            type="email"
            id="email"
            className={`w-full ${errors.email ? 'p-invalid' : ''}`}
          />
          {errors.email && (
            <p className="text-red-600 mt-1">{errors.email?.message}</p>
          )}
        </div>
        <div className="mb-5">
          <label
            htmlFor="mobile"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            Mobile
          </label>

          <InputText
            {...register('mobile')}
            type="mobile"
            id="mobile"
            className={`w-full ${errors.mobile ? 'p-invalid' : ''}`}
          />
          {errors.mobile && (
            <p className="text-red-600 mt-1">{errors.mobile?.message}</p>
          )}
        </div>
        <div className="mb-5">
          <label
            htmlFor="dob"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            Date of Birth
          </label>
          <Controller
            name="dob"
            {...{ control }}
            render={({ field: { name, onChange, value, onBlur } }) => {
              return (
                <>
                  <Calendar
                    showButtonBar
                    className={`w-full ${errors.dob ? 'p-invalid' : ''}`}
                    {...{ name, onBlur }}
                    value={formatInboundDate(value)}
                    onChange={({ value }) => {
                      onChange(formatOutBoundDate(value));
                    }}
                  />
                </>
              );
            }}
          />
          {errors.dob && (
            <p className="text-red-600 mt-1">{errors.dob?.message}</p>
          )}
        </div>
        <div className="mb-5">
          <label
            htmlFor="doj"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            Date Joined
          </label>
          <Controller
            name="doj"
            {...{ control }}
            render={({ field: { name, onChange, value, onBlur } }) => {
              return (
                <>
                  <Calendar
                    showButtonBar
                    className={`w-full ${errors.dob ? 'p-invalid' : ''}`}
                    {...{ name, onBlur }}
                    value={formatInboundDate(value)}
                    onChange={({ value }) => {
                      onChange(formatOutBoundDate(value));
                    }}
                  />
                </>
              );
            }}
          />
          {errors.doj && (
            <p className="text-red-600 mt-1">{errors.doj?.message}</p>
          )}
        </div>
        <div className="flex gap-2">
          <Button disabled={!isValid} type="submit">
            Submit
          </Button>
          <Button onClick={onCloseModal} severity="secondary" type="button">
            Cancel
          </Button>
        </div>
      </form>
    </>
  );
};

// apps/vue-client/src/features/employees/EmployeeForm.vue
<template>
  <form @submit="submitHandler" novalidate>
    <div class="mb-5">
      <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >Name</label
      >
      <InputText v-model="name" v-bind="nameAttrs" type="text" id="name" class="w-full" />
      <p class="text-red-600 mt-1" v-if="errors.name">
        {{ errors.name }}
      </p>
    </div>
    <div class="mb-5">
      <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >Email</label
      >
      <InputText v-model="email" v-bind="emailAttrs" type="text" id="email" class="w-full" />
      <p class="text-red-600 mt-1" v-if="errors.email">
        {{ errors.email }}
      </p>
    </div>
    <div class="mb-5">
      <label for="mobile" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >Mobile</label
      >
      <InputText v-model="mobile" v-bind="mobileAttrs" type="text" id="mobile" class="w-full" />
      <p class="text-red-600 mt-1" v-if="errors.mobile">
        {{ errors.mobile }}
      </p>
    </div>
    <div class="mb-5">
      <label for="dob" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >Date of Birth</label
      >
      <Calendar
        show-button-bar
        append-to="body"
        class="w-full"
        v-bind="dobAttrs"
        @update:model-value="dob = formatOutBoundDate($event)"
        :model-value="formatInboundDate(dob)"
      />
      <p class="text-red-600 mt-1" v-if="errors.dob">
        {{ errors.dob }}
      </p>
    </div>
    <div class="mb-5">
      <label for="doj" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >Date Joined</label
      >
      <Calendar
        show-button-bar
        append-to="body"
        class="w-full"
        v-bind="dojAttrs"
        @update:model-value="doj = formatOutBoundDate($event)"
        :model-value="formatInboundDate(doj)"
      />
      <p class="text-red-600 mt-1" v-if="errors.doj">
        {{ errors.doj }}
      </p>
    </div>
    <div class="flex gap-1">
      <Button :disabled="!meta.valid" type="submit">Submit</Button>
      <Button severity="secondary" @click="$emit('onCloseModal')" type="button">Cancel</Button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { useMutation } from '@tanstack/vue-query';
import { format } from 'date-fns';
import Button from 'primevue/button';
import Calendar from 'primevue/calendar';
import InputText from 'primevue/inputtext';
import { useForm } from 'vee-validate';
import { date, object, string } from 'yup';
import { createEmployee, updateEmployee, type Employee } from 'crud-utils';
import { useToast } from 'primevue/usetoast';

const toast = useToast();

const { employee } = defineProps<{
  employee?: Employee;
}>();

const emit = defineEmits<{
  onCloseModal: [];
}>();

const { defineField, handleSubmit, errors, meta } = useForm<Employee>({
  initialValues: { ...employee },
  validationSchema: object({
    name: string().required(),
    email: string().required().email(),
    mobile: string().required(),
    dob: date().required(),
    doj: date().required(),
  }),
});

const [name, nameAttrs] = defineField('name');
const [email, emailAttrs] = defineField('email');
const [mobile, mobileAttrs] = defineField('mobile');
const [dob, dobAttrs] = defineField('dob');
const [doj, dojAttrs] = defineField('doj');

const { mutate: createMutation } = useMutation<Employee, Error, Omit<Employee, 'employeeId'>>({
  mutationKey: ['createEmployee'],
  mutationFn(employee) {
    return createEmployee(employee);
  },
  onSuccess() {
    showSuccessfulToast('Employee Successfully Created');
    onClose();
  },
});

const { mutate: updateMutation } = useMutation<Employee, Error, Partial<Employee>>({
  mutationKey: ['createEmployee'],
  mutationFn(employee) {
    return updateEmployee(employee.employeeId!, employee);
  },
  onSuccess() {
    showSuccessfulToast('Employee Successfully Updated');
    onClose();
  },
});

const formatInboundDate = (inboundDate?: string) => {
  if (inboundDate) {
    return new Date(inboundDate);
  }
  return '';
};
const formatOutBoundDate = (outboundDate: Date) => {
  if (outboundDate) {
    return format(new Date(outboundDate), 'LL-dd-yyyy');
  }
  return '';
};

const submitHandler = handleSubmit((values) => {
  if (employee) {
    updateMutation(values);
    return;
  }
  createMutation(values);
});

function onClose() {
  emit('onCloseModal');
}

function showSuccessfulToast(detail: string) {
  toast.add({
    severity: 'success',
    summary: 'Success',
    detail: detail,
    life: 3000,
  });
}
</script>
